const reason = 'ERROR'

alert(reason)
